export const fshLogAreaOrder = [
  'Limsa Lominsa Upper Decks',
  'Limsa Lominsa Lower Decks',
  'Middle La Noscea',
  'Lower La Noscea',
  'Eastern La Noscea',
  'Western La Noscea',
  'Upper La Noscea',
  'Outer La Noscea',
  'Mist',
  'New Gridania',
  'Old Gridania',
  'Central Shroud',
  'East Shroud',
  'South Shroud',
  'North Shroud',
  'The Lavender Beds',
  'Western Thanalan',
  'Central Thanalan',
  'Eastern Thanalan',
  'Southern Thanalan',
  'Northern Thanalan',
  'The Goblet',
  'Coerthas Central Highlands',
  'Coerthas Western Highlands',
  'Mor Dhona',
  'The Sea of Clouds',
  'Azys Lla',
  'The Dravanian Forelands',
  'The Dravanian Hinterlands',
  'The Churning Mists',
  'Rhalgr\'s Reach',
  'The Fringes',
  'The Peaks',
  'The Lochs',
  'The Ruby Sea',
  'Yanxia',
  'The Azim Steppe',
  'Kugane',
  'Shirogane',
  'The Crystarium',
  'Eulmore',
  'Lakeland',
  'Kholusia',
  'Amh Araeng',
  'Il Mheg',
  'The Rak\'tika Greatwood',
  'The Tempest',
  'Old Sharlayan',
  'Labyrinthos',
  'Radz-at-Han',
  'Thavnair',
  'Garlemald',
  'Mare Lamentorum',
  'Ultima Thule',
  'Elpis',
  // These are all grouped under The Endeavor in the db but in separate areas ingame
  'Galadion Bay',
  'The Southern Strait of Merlthor',
  'The Northern Strait of Merlthor',
  'Rhotano Sea',
  'The Cieldalaes',
  'The Bloodbrine Sea',
  'The Rothlyt Sound',
  'The Endeavor',
  // not in the log in-game. db groups it with The Diadem
  'The Doman Enclave',
  // not in the log in-game
  'The Diadem',
];

export const fshLogSpotOrder = [
  'Limsa Lominsa Upper Decks',
  'Limsa Lominsa Lower Decks',
  'Zephyr Drift',
  'Rogue River',
  'West Agelyss River',
  'Summerford',
  'Nym River',
  'Woad Whisper Canyon',
  'The Mourning Widow',
  'Moraby Bay',
  'Cedarwood',
  'Oschon\'s Torch',
  'Candlekeep Quay',
  'Moraby Drydocks',
  'Empty Heart',
  'The Salt Strand',
  'Blind Iron Mines',
  'South Bloodshore',
  'Costa del Sol',
  'North Bloodshore',
  'Rhotano Sea (Privateer Forecastle)',
  'Rhotano Sea (Privateer Sterncastle)',
  'Hidden Falls',
  'East Agelyss River',
  'Raincatcher Gully',
  'The Juggernaut',
  'Red Mantis Falls',
  'North Isle of Endless Summer',
  'Swiftperch',
  'Skull Valley',
  'The Brewer\'s Beacon',
  'Halfstone',
  'Isles of Umbra Northshore',
  'The Ship Graveyard',
  'Sapsa Spawning Grounds',
  'Isles of Umbra Southshore',
  'Reaver Hide',
  'Oakwood',
  'Fool Falls',
  'Bronze Lake Shallows',
  'Northeast Bronze Lake',
  'The Long Climb',
  'Northwest Bronze Lake',
  'Mist',
  'Jadeite Flood',
  'Lower Black Tea Brook',
  'Whispering Gorge',
  'Upper Black Tea Brook',
  'The Vein',
  'The Mirror',
  'Everschade',
  'Hopeseed Pond',
  'Haukke Manor',
  'Sweetbloom Pier',
  'Springripple Brook',
  'Sanctum of the Twelve',
  'Verdant Drop',
  'Sylphlands',
  'Upper Hathoeva River',
  'Lower Hathoeva River',
  'East Hathoeva River',
  'Middle Hathoeva River',
  'Goblinblood',
  'Rootslake',
  'Urth\'s Gift',
  'Murmur Rills',
  'Fallgourd Float',
  'Proud Creek',
  'Lake Tahtotl',
  'The Lavender Beds',
  'Nophica\'s Wells',
  'The Footfalls',
  'Vesper Bay',
  'Crescent Cove',
  'The Silver Bazaar',
  'Cape Westwind',
  'Moondrip',
  'Parata\'s Peace',
  'Upper Soot Creek',
  'Lower Soot Creek',
  'The Clutch',
  'The Unholy Heir',
  'North Drybone',
  'South Drybone',
  'Yugr\'am River',
  'The Burning Wall',
  'Burnt Lizard Creek',
  'Zahar\'ak',
  'Forgotten Springs',
  'Sagolii Desert',
  'Sagolii Dunes',
  'Bluefog',
  'Ceruleum Field',
  'The Goblet',
  'Coerthas River',
  'Daniffen Pass',
  'The Nail',
  'Dragonhead Latrines',
  'Exploratory Ice Hole',
  'The Weeping Saint',
  'Snowcloak',
  'Sea of Clouds',
  'Witchdrop',
  'Riversmeet',
  'Greytail Falls',
  'Unfrozen Pond',
  'Clearpool',
  'Dragonspit',
  'South Banepool',
  'Ashpool',
  'West Banepool',
  'North Silvertear',
  'The Deep Tangle',
  'Singing Shards',
  'Rathefrost',
  'The Tangle',
  'The North Shards',
  'Voor Sian Siran',
  'The Eddies',
  'Cloudtop',
  'The Blue Window',
  'Mok Oogl Island',
  'Alpha Quadrant',
  'Aetherochemical Spill',
  'Hyperstellar Downconverter',
  'Delta Quadrant',
  'The Pappus Tree',
  'The Habisphere',
  'The Flagship',
  'The Hundred Throes',
  'Whilom River',
  'The Smoldering Wastes',
  'The Iron Feast',
  'Mourn',
  'West Mourn',
  'Anyx Old',
  'Halo',
  'Thaliak River',
  'Quickspill Delta',
  'Upper Thaliak River',
  'Middle Thaliak River',
  'Eil Tohm',
  'Greensward',
  'Weston Waters',
  'Landlord Colony',
  'Sohm Al Summit',
  'Tharl Oom Khash',
  'Upper Mirage Creek',
  'Rhalgr\'s Reach',
  'The Outer Fist',
  'Timmon Beck',
  'Dimwold',
  'The Comet\'s Tail',
  'The Velodyna River',
  'Mirage Creek',
  'Grymm & Enid',
  'The Slow Wash',
  'Heather Falls',
  'The Ephor',
  'The Bull\'s Bath',
  'The Arms of Meed',
  'Loch Seld',
  'The Ruby Price',
  'Hells\' Lid',
  'The Isle of Bekko',
  'Shoal Rock',
  'Onokoro',
  'Isari',
  'The Isle of Zekki',
  'The Heron\'s Nest',
  'The Heron\'s Way',
  'Namai',
  'The One River (East)',
  'The One River (West)',
  'Plum Spring',
  'Prism Canyon',
  'Prism Lake',
  'Mercantile Docks',
  'Doma Castle',
  'Nem Khaal',
  'Hak Khaal',
  'Upper Yat Khaal',
  'Azim Khaat',
  'Tao Khaal',
  'Lower Yat Khaal',
  'Dotharl Khaa',
  'Kugane Piers',
  'Shirogane',
  'The Silver Canal',
  'The Trivium',
  'The Quadrivium',
  'Crystarium Personal Suites',
  'The Derelicts',
  'The Rift of Sighs',
  'The Rusted Reservoir',
  'The Source',
  'Sullen',
  'The Isle of Ken',
  'Upper Watts River',
  'White Oil Falls',
  'Lower Watts River',
  'Sharptongue Drip',
  'The Western Kholusian Coast',
  'Seagazer Shoals',
  'The Eastern Kholusian Coast',
  'The River of Sand',
  'The Nabaath Severance',
  'The Hills of Amber',
  'Handmirror Lake',
  'Longmirror Lake',
  'The Haughty One',
  'The Jealous One',
  'The Spoiled One',
  'Saint Fathric\'s Temple',
  'Father Collard\'s Failings',
  'Lake Tusi Mek\'ta',
  'The Red Chalice',
  'The Lozatl',
  'South Mjrl\'s Regret',
  'Woven Oath',
  'Mjrl\'s Tears',
  'The Flounders\' Floor',
  'Where the Dry Return',
  'Northwest Caliban Gorge',
  'West Caliban Gap',
  'East Caliban Gap',
  'Purpure',
  'The Norvrandt Slope',
  'Scholar\'s Harbor',
  'Oinops',
  'Reflecting Pool',
  'Unmoved Source Alpha',
  'The Mover Alpha',
  'Unmoved Source Beta',
  'The Mover Beta',
  'Deepmoat',
  'Meghaduta',
  'Yedlihmad',
  'The Thavnairian Coast',
  'The Great Runoff',
  'Giantsgall Grounds',
  'The Wakeful Torana',
  'Ksiroda',
  'Pavana\'s Remorse',
  'The Font of Maya',
  'The Perfumed Tides',
  'The Eblan Thaw',
  'The Stainless Course',
  'Greatest Endsvale',
  'The Chlorophospond',
  'The Frozen Fissure',
  'Apohelos 18-α',
  'Apohelos 18-β',
  'Apohelos 18-γ',
  'The Wellspring of Regret',
  'Elegeia',
  'Limne 18',
  'Limne 3-α',
  'Limne 3-β',
  'Rumination\'s Ramble',
  'The Lower Hungering Gardens',
  'Lethe',
  'Outer Galadion Bay',
  'Galadion Spectral Current',
  'The Southern Strait of Merlthor',
  'Southern Merlthor Spectral Current',
  'The Northern Strait of Merlthor',
  'Northern Merlthor Spectral Current',
  'Open Rhotano Sea',
  'Rhotano Spectral Current',
  'Cieldalaes Margin',
  'Cieldalaes Spectral Current',
  'Open Bloodbrine Sea',
  'Bloodbrine Spectral Current',
  'Outer Rothlyt Sound',
  'Rothlyt Spectral Current',
  'Outer Galadion Bay',
  'Galadion Spectral Current',
  'The Southern Strait of Merlthor',
  'Southern Merlthor Spectral Current',
  'The Northern Strait of Merlthor',
  'Northern Merlthor Spectral Current',
  'Open Rhotano Sea',
  'Rhotano Spectral Current',
  'Cieldalaes Margin',
  'Cieldalaes Spectral Current',
  'Open Bloodbrine Sea',
  'Bloodbrine Spectral Current',
  'Outer Rothlyt Sound',
  'Rothlyt Spectral Current',
  // Doman Enclave and Diadem not in log ingame
  'The Doman Enclave',
  'Diadem Skysprings',
  'Diadem Grotto',
  'Southern Diadem Lake',
  'Secluded Diadem Pond',
  'Northern Diadem Lake',
  'Blustery Cloudtop',
  'Calm Cloudtop',
  'Swirling Cloudtop',
  'Windswept Cloudtop',
  'Windbreaking Cloudtop',
  'Buffeted Cloudtop',
];

